### PR TITLE
Create EasyFFT struct, add plot recipe

### PR DESCRIPTION
**Pull request by gustaphe**
With this PR:

```julia
using EasyFFTs, Plots
t = 0.0:1e-2:1.0
y = cos.(2pi*10*t) .+ 3.0*sin.(2pi*25*t) .+0.1randn(size(t))
fft = easyfft(y, 1e2)
scatter(fft)
```
fft

Because there's an `iterate` method, `(f, r) = easyfft(y, f_s)` still works.

(Making `EasyFFT` a struct also means you could dispatch other functions to this, for instance the `sortperm` example could be made a single function call)

### CODE REVIEW

**Comment by KronosTheLate** [comment]
That looks awesome! I will check it out in more detail when I find some time.

I personally prefer Makie, but have never experimented with Makie recipes. Have you? Do you know of any technical difficulties down that road? E.g. terrible load-times, non-satisfactory results or something else?

**Comment by gustaphe** [comment]
I never used Makie, been meaning to try it out. It seems like a fairly heavy dependency, so maybe `Requires` should be used for that. And I can't quite figure out if there is a method to have a type recipe create a layout like this. Someone who knows Makie should probably make that PR. Either way, there's very little harm in using `RecipesBase` (from `Plots.jl`) as well, since it's light weight. And you'll want the type too.

When it comes to this PR, I should do some documentation before it's merged, just wanted to see how you feel about it in theory.

**Comment by KronosTheLate** [comment]
Overall your changes all look great! Thanks.

Tiny nitpick - I would be hesitant to make 'fft' a variable name in the examples, as it is the name of the FFTW function. That was my only comment after reading the changes - I will test them soon (a lot of reports due around this and next week, so I will have to see when I can take the guilty-pleasure time for it.

**Comment by KronosTheLate** [comment]
I would like a show method for the EasyFFTs object. I don't know if defining a unicode-plots show method would be desired? The current show method however is a mess:
```
julia> easyfft(sin.(0:0.01:1))
EasyFFTs.EasyFFT([0.0, 0.009900990099009901, 0.019801980198019802, 0.0297029702970297, 0.039603960396039604, 0.04950495049504951, 0.0594059405940594, 0.06930693069306931, 0.07920792079207921, 0.0891089108910891  …  0.40594059405940597, 0.4158415841584158, 0.42574257425742573, 0.43564356435643564, 0.44554455445544555, 0.45544554455445546, 0.46534653465346537, 0.4752475247524752, 0.48514851485148514, 0.49504950495049505], ComplexF64[0.9096102318341125 + 0.0im, -0.032657591824553654 + 0.27390596591600924im, -0.014278116417669469 + 0.13415163319037832im, -0.010952916915019699 + 0.08896853313403863im, -0.009794752611907652 + 0.06649132172625791im, -0.009259682614352555 + 0.053006582700814604im, -0.008969297430852619 + 0.04399964000328758im, -0.008794302600836862 + 0.03754596097208787im, -0.00868076984896109 + 0.03268600113467982im, -0.008602958634818227 + 0.028887575101336577im  …  -0.008327347723030095 + 0.002527351252505636im, -0.008326903199869047 + 0.0022477289085125907im, -0.0083265168673407 + 0.0019727785057102733im, -0.008326185438959483 + 0.001701864165737185im, -0.008325906155695723 + 0.0014343839797267127im, -0.008325676735908111 + 0.0011697643631347655im, -0.008325495334946314 + 0.0009074549183954577im, -0.008325360513171365 + 0.0006469237038923698im, -0.008325271211428434 + 0.00038765282016959104im, -0.008325226733246281 + 0.00012913423378935359im])
```

The documentation (docstrings and readme) and examples (readme) also need updating, which naturally should wait for e.g. such a change in show method. Do you like the idea of a Unicode plot show method, or can you imagine a better way? Perhaps a table showing the most prominent frequencies akin to one of the readme examples?

**Comment by gustaphe** [comment]
A unicodeplot might be a bit overkill. How about something like `EasyFFT with 1001 samples, showing a dominant frequencies at f = 0.0, 4.0 and 5.0`? doesn't take too much space in the repl but lets you distinguish between different objects.

**Comment by KronosTheLate** [comment]
That sounds great by me. I am not sure - would the user generally be most interested in peaks, or maximal values? If there is a single dominant peak, that all the displayed frequencies are likely to come from the same peak. On the other hand, it would be impossible to know how many peaks would be displayed if all are found. Perhaps finding all peaks, and showing up to e.g. 5? I imagine adding a dependency like https://github.com/halleysfifthinc/Peaks.jl or https://github.com/tungli/Findpeaks.jl for that. Perhaps a minimal internal implementation would make sense to avoid the dependency.

**Comment by KronosTheLate** [comment]
For plotting discrete values, I always found a so-called `stem`-plot to be the most aproporiate. If you agree/don't mind, I could change the plot in `assets`.

**Pull request merged**
