### PR TITLE
typos - style - enhance plots (borders)

### PR DESCRIPTION
**Pull request by t-bltg**
Hi @KronosTheLate, a few typos, and add syntax coloring in `Readme.md`.

Also, adding axes labels (and maybe units) is quite useful.

For the border issue observed on discourse, you can use `border=:dotted`, as explained in https://github.com/JuliaPlots/UnicodePlots.jl#know-issues.

### CODE REVIEW

**Comment by KronosTheLate** [comment]
Nice, thanks. All the changes look good to me - anything you want to discuss or add before merging?

**Comment by t-bltg** [comment]
It was only the obvious changes: I didn't dig further, and I must admit I am biased towards `UnicodePlots` related stuff.
It would be great to adjust the `discourse` post with these changes after merge :)

**Comment by KronosTheLate** [comment]
The discourse post is updated. Thanks ^_^

**Comment by t-bltg** [comment]
Thanks for using `UnicodePlots` !

**Comment by KronosTheLate** [comment]
> Thanks for using `UnicodePlots` !

Arre you kidding me? It is one of my favorite Julia packges. Simply genius ^_^. If you are a key contrubutor to it, thank you for your work <3

**Pull request merged**
